name: "update golang version from Dockerfile"
pipelineid: "{{ .pipelineid }}"
autodiscovery:
  # {{ if and .scm.default.enabled }}
  scmid: default
  actionid: default
  # {{ end }}
  groupby: all
  crawlers:
    dockerfile:
      digest: false
      only:
        - images:
            - "registry.suse.com/bci/golang"
      versionfilter:
        kind: semver
        pattern: "{{ .pattern }}"
